[build]
builder = "nixpacks"
buildCommand = "echo 'Building both frontend and backend...'"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.envs]
PYTHON_VERSION = "3.10"
NODE_VERSION = "18" 